version: "3.9"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile-devel
    volumes:
      - .:/app:cached
      - /app/local
      - cache-vol:/app/.cache
volumes:
  cache-vol: